MAP_SIZE = 256

# *_AMOUNT : Amount of given terrain, out of 1
# *_WIBBLE_BASE : Large-scale wibbliness. Larger is more wibbly.
# *_WIBBLE_SCALE : Small-scale wibbliness. Smaller is more wibbly.

LAND_AMOUNT = 0.6
LAND_WIBBLE_BASE = 40
LAND_WIBBLE_SCALE = 1.5

DEEP_WATER_AMOUNT = 0.3

SCATTER_WIBBLE_BASE = 20

SNOW_AMOUNT = 0.9
SNOW_WIBBLE_SCALE = 0.8
SNOW_MIN_HEIGHT = 24

ROCK_AMOUNT_GRASS = 0.08
ROCK_AMOUNT_SNOW  = 0.16
ROCK_AMOUNT_WATER = 0.06
ROCK_WIBBLE_SCALE = 0.88

SAND_AMOUNT = 0.8
SAND_WIBBLE_SCALE = 0.88

TREE_AMOUNT_GRASS = 0.2
TREE_AMOUNT_SNOW  = 0.1
TREE_WIBBLE_SCALE = 0.8

BOG_AMOUNT = 0.15
BOG_WIBBLE_SCALE = 1.8
BOG_MAX_DEPTH = 1
BOG_MAX_HEIGHT = 3

NUM_STREAMS = 100