MAP_SIZE = 256

# *_AMOUNT : Amount of given terrain, out of 1
# *_WIBBLE_BASE : Large-scale wibbliness. Larger is more wibbly.
# *_WIBBLE_SCALE : Small-scale wibbliness. Smaller is more wibbly.

LAND_AMOUNT = 0.6
LAND_WIBBLE_BASE = 40
LAND_WIBBLE_SCALE = 1.5

DEEP_WATER_AMOUNT = 0.3

TREE_WIBBLE_BASE = 10
TREE_WIBBLE_SCALE = 0.8

ROCK_WIBBLE_BASE = 10
ROCK_WIBBLE_SCALE = 0.85

BOG_WIBBLE_BASE = 10
BOG_WIBBLE_SCALE = 1.8
BOG_AMOUNT = 0.15
BOG_MAX_DEPTH = 1
BOG_MAX_HEIGHT = 3

SAND_AMOUNT = 0.8
SNOW_AMOUNT = 0.9
SNOWLINE = 24          #Above waterline

TREE_AMOUNT_GRASS = 0.2
TREE_AMOUNT_SNOW  = 0.1

ROCK_AMOUNT_GRASS = 0.1
ROCK_AMOUNT_SNOW  = 0.2

NUM_STREAMS = 100